# Distances in 1000km
# Orbital period in years

spaceBackground = "black"
addStars = true
spaceShipStartingPosition = "mars"

[colors]
black = "#030303"
white = "#ffffff"

# ğŸŒ‘ Sun
[planets.sun]
name = "Sun"
diameter = 1392
distanceFromOrbitCenter = 0
texturePath = "sun/sun-texture.jpg"
emissiveMapPath = "sun-texture.jpg"
numberOfSegments = 128

[planets.sun.otherMaterialProps]
emissive = "#f3f3ee"
emissiveIntensity = 2

# Venus
[planets.venus]
name = "Venus"
diameter = 12.104
distanceFromOrbitCenter = 108_200
texturePath = "venus/venus-surface-texture.jpg"
emissiveMapPath = "venus/venus-surface-texture.jpg"
numberOfSegments = 128
orbitalPeriod = 0.6658
 
[planets.venus.otherMaterialProps]
emissive = "#f3f3ee"
emissiveIntensity = 0.05

# ğŸŒ Earth
[planets.earth]
name = "Earth"
diameter = 12.756
distanceFromOrbitCenter = 149_600
texturePath = "earth-texture.jpg"
normalMapPath = "earth_normal_map.jpg"
specularMapPath = "earth_specular_map.jpg"   
emissiveMapPath = "earth-texture.jpg"
numberOfSegments = 128
orbitalPeriod = 1
 
[planets.earth.otherMaterialProps]
emissive = "#f3f3ee"
emissiveIntensity = 0.05


# ğŸŒ• Moon
[moons.earthMoon]
parentPlanet = "earth"
name = "Earth Moon"
diameter = 3.476
distanceFromOrbitCenter = 384.4
texturePath = "moon-texture.jpg" 
normalMapPath = "moon-normal-map.jpg"
emissiveMapPath = "moon-texture.jpg"
numberOfSegments = 128
orbitalPeriod = 0.0748
 
[planets.earthMoon.otherMaterialProps]
emissive = "#f3f3ee"
emissiveIntensity = 0.1


# ğŸ”´ Mars
[planets.mars]
name = "Mars"
diameter = 6.794
distanceFromOrbitCenter = 227_900
texturePath = "mars-texture.jpg"
normalMapPath = "mars-normal-map.jpg"
emissiveMapPath = "mars-texture.jpg"
numberOfSegments = 128
orbitalPeriod = 1.8821
 
[planets.mars.otherMaterialProps]
emissive = "#f3f3ee"
emissiveIntensity = 0.05


# ğŸ”´ Mercury
[planets.mercury]
name = "Mercury"
diameter = 4.880
distanceFromOrbitCenter = 57_900
texturePath = "mercury-texture.jpg"
normalMapPath = "mercury-normal-map.jpg"
emissiveMapPath = "mercury-texture.jpg"
numberOfSegments = 128
orbitalPeriod = 0.2410
 
[planets.mercury.otherMaterialProps]
emissive = "#f3f3ee"
emissiveIntensity = 0.05


# ğŸ”´ Jupiter
[planets.jupiter]
name = "Jupiter"
diameter = 142.984
distanceFromOrbitCenter = 778_300
texturePath = "jupiter/jupiter-texture.jpg"
emissiveMapPath = "jupiter/jupiter-texture.jpg"
numberOfSegments = 128
orbitalPeriod = 11.86
 
[planets.jupiter.otherMaterialProps]
emissive = "#f3f3ee"
emissiveIntensity = 0.05